import localFont from "next/font/local";
import "./globals.css";
import Toast from "@/components/Toast";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toast />
        <Navbar />
        <div className="flex">
          <aside
            className="sticky top-16"
            style={{ height: "calc(100vh - 4rem)" }}
          >
            <Sidebar />
          </aside>
          <main className="w-full m-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
